export type Locale = "zh" | "en" | "ja";

const messages: Record<Locale, Record<string, string>> = {
  zh: {
    brand: "车鉴 · Vehicle Lens",
    vinTab: "VIN 查询", vinTabHint: "输入17位车辆识别码", manualTab: "手动车型查询", manualTabHint: "按年款与车型逐级选择",
    heroText: "结合 NHTSA VIN 解码与五级车型数据库，快速定位年款、品牌、车系、配置款和发动机。",
    combinations: "车型组合", coveredYears: "覆盖年份", levels: "属性层级", vinSmart: "VIN 智能识别",
    vinLabel: "输入17位车辆识别码", vinPlaceholder: "例如 JTDKN3DU4A0000000", decoding: "识别中…", decode: "解析 VIN",
    example: "试试示例：", random: "随机 VIN", fetching: "获取中…", nhtsaResult: "NHTSA 解码结果",
    year: "年款", make: "品牌", model: "车系", body: "车身", manufacturer: "制造商", trim: "配置款", engine: "发动机", fuel: "燃料",
    unknown: "未知", cannotDetermine: "无法判断", aiParsing: "AI 补充解析", aiParsingText: "AI 正在分析 NHTSA 缺失的车型字段…",
    aiFailed: "AI 补充解析未完成", aiCandidate: "AI 候选车型", sourcedInference: "有来源推断", unverified: "未经核验",
    confidence: "可信度", confidenceHigh: "较高", confidenceMedium: "中等", confidenceLow: "低", possibleModels: "可能的车系",
    candidateNotice: "以下为模型候选，不是确认结果", lowConfidence: "低可信度", possibleTrims: "可能配置：", noMoreAttributes: "暂无更多车型属性",
    manualTitle: "手动车型查询", manualIntro: "无需 VIN，按顺序选择车辆属性。", lookupMethods: "车型查询方式", select: "请选择", loading: "加载中…", noTrim: "无配置款", noEngine: "未提供发动机",
    currentVehicle: "当前车型", noMoreData: "该车型没有更多配置数据", fullMatch: "完整匹配", trimMatch: "配置款匹配", modelMatch: "车系匹配",
    startFromYear: "从年款开始，逐级缩小车型范围", specifications: "车辆规格详情", nhtsaSource: "数据来源 · NHTSA vPIC",
    modelSource: "车型级资料 · D1 + NHTSA CVS", searchingImage: "正在异步查找同款车型参考图…", referenceImage: "同款车型参考图",
    author: "作者：", commonsContributor: "Wikimedia Commons 贡献者", imageGallery: "车型参考图片画廊", viewImage: "查看车型参考图", inferredReferenceImage: "AI 推测车型参考图", inferredImageNotice: "图片按 AI 的首选候选车型检索，仅用于外观参考，不代表 VIN 车型已被确认。", viewLicense: "查看授权", licenseAtSource: "授权信息见来源页", viewSource: "查看图片来源 ↗", noImage: "Wikimedia Commons 暂未找到可靠的同款车型参考图",
    queriedVin: "查询 VIN", vehicleCriteria: "车型条件", noStandardName: "NHTSA 未返回标准车型名称", noSummary: "暂无车辆摘要",
    nhtsaListed: "NHTSA 已收录", loadingSpecs: "正在异步加载车型规格…", modelReference: "车型级参考资料",
    basicInfo: "基本信息", series: "系列", vehicleType: "车辆类型", powertrain: "动力与传动", displacement: "排量", cylinders: "气缸数",
    engineLayout: "发动机布局", engineModel: "发动机型号", horsepower: "发动机功率", primaryFuel: "主要燃料", secondaryFuel: "辅助燃料",
    electrification: "电气化类型", driveType: "驱动形式", transmission: "变速器", transmissionSpeeds: "变速器挡位", bodyManufacturing: "车身与制造",
    doors: "车门数", seats: "座位数", brakes: "制动系统", gvwr: "总质量等级", plantCountry: "生产国家", plantState: "生产州/省", plantCity: "生产城市",
    modelInfo: "车型信息", currentTrim: "当前配置款", currentEngine: "当前发动机", nhtsaRegistration: "NHTSA 车型登记", localPaths: "本地车型组合",
    availableTrims: "可选配置款", availableEngines: "可选发动机", dimensions: "尺寸与重量", length: "车长", width: "车宽", height: "车高", wheelbase: "轴距",
    curbWeight: "整备质量", frontTrack: "前轮距", rearTrack: "后轮距", weightDistribution: "前后配重", dataScope: "数据范围", specSource: "规格来源",
    configSource: "配置来源", localDb: "本地五级车型数据库", dataLevel: "数据级别", modelData: "车型级参考数据", missing: "未提供",
    vinSpecsNote: "该区域仅展示 NHTSA vPIC 对当前 VIN 返回的字段；“未提供”表示接口没有返回可靠值。", manualSpecsNote: "该区域基于年款、品牌和车系异步查询车型级资料；尺寸来自 NHTSA Canadian Vehicle Specifications，配置统计来自本地 D1。没有真实 VIN 时无法确定工厂、具体驱动和车辆序列信息。", scopeNote: "车辆图片、市场价格和具体在售配置不属于 vPIC 数据。",
    vinGuide: "VIN 字段说明", vinChars: "VIN 字符", determined: "已确定", parsingStructure: "正在解析 VIN 结构…", queriedVinCaption: "NHTSA 查询 VIN",
    pseudoVin: "17位结构伪码", allChars: "每个字符均来自本次 VIN 查询", starUnknown: "代表当前数据无法确定的字符", vinDiagram: "VIN 结构图", wmi: "WMI 制造商",
    vds: "VDS 车辆特征", checkDigit: "校验位", modelYear: "车型年款", plant: "装配工厂", serial: "生产序列号", segmentDetails: "分段说明",
    nhtsaSegmentHint: "以下明确列出 NHTSA vPIC 返回的车型信息。", manualSegmentHint: "VIN 每一段由不同规则生成，不能仅凭车型名称反向推算。",
    vinProvided: "VIN 已提供", pending: "待补充", nhtsaQueryResult: "NHTSA 查询结果", important: "重要说明",
    statsLabel: "数据库概览", noVinYear: "VIN 未返回有效年份，请使用手动查询。", noLocalMake: "已识别年份，但本地库没有对应品牌。", noLocalModel: "已匹配到品牌，本地库暂无对应车系。", localTrimMatched: "已在本地车型库匹配到配置款。", localModelMatched: "已在本地车型库匹配到车系。", randomVinFailed: "无法获取随机 VIN：",
    error_database: "车型数据库加载失败", error_vehicleQuery: "车型查询失败", error_DATABASE_NOT_READY: "车型数据库尚未导入", error_DATABASE_ERROR: "车型数据库查询失败", error_INVALID_ARGUMENT: "车型查询参数无效", error_INVALID_JSON: "请求格式无效", error_INVALID_VIN: "VIN 必须为17位，且不能包含 I、O、Q", error_INVALID_VEHICLE: "车型参数不完整", error_VIN_UNAVAILABLE: "VIN 解析服务暂时不可用", error_VIN_PATTERN_UNAVAILABLE: "VIN 字段说明暂时无法生成", error_VEHICLE_DETAILS_UNAVAILABLE: "车型详情暂时无法加载", error_IMAGE_LOOKUP_UNAVAILABLE: "车型参考图暂时无法加载", error_RANDOM_VIN_UNAVAILABLE: "随机 VIN 服务暂时不可用，请稍后重试", error_GEMINI_NOT_CONFIGURED: "AI 补充解析尚未配置", error_GEMINI_TIMEOUT: "AI 补充解析超时，请稍后重试", error_GEMINI_RATE_LIMITED: "AI 查询额度暂不可用，请稍后重试", error_GEMINI_AUTH_FAILED: "AI 服务认证失败，请检查服务配置", error_GEMINI_UNAVAILABLE: "AI 补充解析暂时不可用",
    footer: "VIN 数据来自 NHTSA vPIC；AI 推断与查询结果仅供车型识别参考。",
  },
  en: {}, ja: {},
};

messages.en = {
  brand: "Vehicle Lens", vinTab: "VIN Lookup", vinTabHint: "Enter a 17-character VIN", manualTab: "Manual Lookup", manualTabHint: "Select year and vehicle attributes",
  heroText: "Combine NHTSA VIN decoding with a five-level vehicle database to identify year, make, model, trim, and engine.", combinations: "Combinations", coveredYears: "Years", levels: "Attribute levels",
  vinSmart: "VIN Intelligence", vinLabel: "Enter a 17-character VIN", vinPlaceholder: "e.g. JTDKN3DU4A0000000", decoding: "Decoding…", decode: "Decode VIN", example: "Example: ", random: "Random VIN", fetching: "Fetching…", nhtsaResult: "NHTSA Decode",
  year: "Year", make: "Make", model: "Model", body: "Body", manufacturer: "Manufacturer", trim: "Trim", engine: "Engine", fuel: "Fuel", unknown: "Unknown", cannotDetermine: "Undetermined",
  aiParsing: "AI Enrichment", aiParsingText: "AI is analyzing vehicle fields missing from NHTSA…", aiFailed: "AI enrichment unavailable", aiCandidate: "AI Candidate Vehicle", sourcedInference: "Source-backed inference", unverified: "Unverified",
  confidence: "confidence", confidenceHigh: "high", confidenceMedium: "medium", confidenceLow: "low", possibleModels: "Possible Models", candidateNotice: "Model candidates, not confirmed results", lowConfidence: "Low confidence", possibleTrims: "Possible trims: ", noMoreAttributes: "No additional attributes",
  manualTitle: "Manual Vehicle Lookup", manualIntro: "No VIN required. Select attributes in order.", lookupMethods: "Vehicle lookup methods", select: "Select ", loading: "Loading…", noTrim: "No trim", noEngine: "Engine not provided", currentVehicle: "Current vehicle", noMoreData: "No additional configuration data", fullMatch: "Full match", trimMatch: "Trim match", modelMatch: "Model match", startFromYear: "Start with the year to narrow the vehicle",
  specifications: "Vehicle Specifications", nhtsaSource: "Source · NHTSA vPIC", modelSource: "Model data · D1 + NHTSA CVS", searchingImage: "Finding reference images asynchronously…", referenceImage: "Model reference image", author: "Author: ", commonsContributor: "Wikimedia Commons contributor", imageGallery: "Vehicle reference image gallery", viewImage: "View reference image", inferredReferenceImage: "AI candidate reference image", inferredImageNotice: "This image search uses the AI system’s top model candidate. It is for visual reference and does not confirm the VIN’s model.", viewLicense: "View license", licenseAtSource: "License on source page", viewSource: "View source ↗", noImage: "No reliable matching image found on Wikimedia Commons",
  queriedVin: "Queried VIN", vehicleCriteria: "Vehicle criteria", noStandardName: "NHTSA returned no standard model name", noSummary: "No vehicle summary", nhtsaListed: "Listed by NHTSA", loadingSpecs: "Loading model specifications…", modelReference: "Model-level reference data",
  basicInfo: "Basic Information", series: "Series", vehicleType: "Vehicle type", powertrain: "Powertrain", displacement: "Displacement", cylinders: "Cylinders", engineLayout: "Engine configuration", engineModel: "Engine model", horsepower: "Horsepower", primaryFuel: "Primary fuel", secondaryFuel: "Secondary fuel", electrification: "Electrification", driveType: "Drive type", transmission: "Transmission", transmissionSpeeds: "Transmission speeds",
  bodyManufacturing: "Body & Manufacturing", doors: "Doors", seats: "Seats", brakes: "Brake system", gvwr: "GVWR", plantCountry: "Plant country", plantState: "Plant state", plantCity: "Plant city", modelInfo: "Vehicle Information", currentTrim: "Selected trim", currentEngine: "Selected engine", nhtsaRegistration: "NHTSA model listing", localPaths: "Local combinations", availableTrims: "Available trims", availableEngines: "Available engines",
  dimensions: "Dimensions & Weight", length: "Length", width: "Width", height: "Height", wheelbase: "Wheelbase", curbWeight: "Curb weight", frontTrack: "Front track", rearTrack: "Rear track", weightDistribution: "Weight distribution", dataScope: "Data Scope", specSource: "Specification source", configSource: "Configuration source", localDb: "Local five-level vehicle database", dataLevel: "Data level", modelData: "Model-level reference", missing: "Not provided", vinSpecsNote: "This section only shows fields returned by NHTSA vPIC for this VIN. “Not provided” means no reliable value was returned.", manualSpecsNote: "Model-level specifications are loaded from the selected year, make, and model. Dimensions come from NHTSA Canadian Vehicle Specifications and configuration counts from local D1. Without a real VIN, plant, exact drivetrain, and serial details cannot be determined.", scopeNote: "Images, market prices, and current retail configurations are outside vPIC data.",
  vinGuide: "VIN Field Guide", vinChars: "VIN characters", determined: "Determined", parsingStructure: "Parsing VIN structure…", queriedVinCaption: "NHTSA VIN", pseudoVin: "17-character pattern", allChars: "Every character comes from the queried VIN", starUnknown: "means the character is currently unknown", vinDiagram: "VIN diagram", wmi: "WMI Manufacturer", vds: "VDS Vehicle Attributes", checkDigit: "Check Digit", modelYear: "Model Year", plant: "Assembly Plant", serial: "Serial Number", segmentDetails: "Segment Details", nhtsaSegmentHint: "NHTSA vPIC results are shown for each segment.", manualSegmentHint: "VIN segments follow manufacturer rules and cannot be derived from a model name alone.", vinProvided: "VIN supplied", pending: "Pending", nhtsaQueryResult: "NHTSA Result", important: "Important", statsLabel: "Database overview", noVinYear: "The VIN did not return a valid year. Use manual lookup.", noLocalMake: "The year was identified, but the local database has no matching make.", noLocalModel: "The make matched, but the local database has no matching model.", localTrimMatched: "Matched a trim in the local vehicle database.", localModelMatched: "Matched a model in the local vehicle database.", randomVinFailed: "Unable to fetch a random VIN: ", error_database: "Failed to load the vehicle database", error_vehicleQuery: "Vehicle lookup failed", error_DATABASE_NOT_READY: "The vehicle database has not been imported", error_DATABASE_ERROR: "Vehicle database query failed", error_INVALID_ARGUMENT: "Invalid vehicle lookup parameters", error_INVALID_JSON: "Invalid request format", error_INVALID_VIN: "VIN must contain 17 characters and cannot include I, O, or Q", error_INVALID_VEHICLE: "Required vehicle parameters are missing", error_VIN_UNAVAILABLE: "VIN decoding is temporarily unavailable", error_VIN_PATTERN_UNAVAILABLE: "VIN field details are temporarily unavailable", error_VEHICLE_DETAILS_UNAVAILABLE: "Vehicle details are temporarily unavailable", error_IMAGE_LOOKUP_UNAVAILABLE: "Vehicle reference images are temporarily unavailable", error_RANDOM_VIN_UNAVAILABLE: "The random VIN service is temporarily unavailable. Please try again.", error_GEMINI_NOT_CONFIGURED: "AI enrichment is not configured", error_GEMINI_TIMEOUT: "AI enrichment timed out. Please try again.", error_GEMINI_RATE_LIMITED: "AI quota is temporarily unavailable. Please try again later.", error_GEMINI_AUTH_FAILED: "AI service authentication failed. Check the service configuration.", error_GEMINI_UNAVAILABLE: "AI enrichment is temporarily unavailable", footer: "VIN data from NHTSA vPIC. AI inferences and results are for vehicle identification reference only.",
};

messages.ja = {
  ...messages.en,
  brand: "車両鑑定 · Vehicle Lens", vinTab: "VIN検索", vinTabHint: "17桁の車台番号を入力", manualTab: "車種を手動検索", manualTabHint: "年式と車両属性を順番に選択",
  heroText: "NHTSAのVIN解析と5階層の車種データベースを組み合わせ、年式・メーカー・車種・グレード・エンジンを特定します。", combinations: "車種構成", coveredYears: "対応年式", levels: "属性階層",
  vinSmart: "VINスマート解析", vinLabel: "17桁のVINを入力", vinPlaceholder: "例 JTDKN3DU4A0000000", decoding: "解析中…", decode: "VINを解析", example: "例：", random: "ランダムVIN", fetching: "取得中…", nhtsaResult: "NHTSA解析結果",
  year: "年式", make: "メーカー", model: "車種", body: "ボディ", manufacturer: "製造会社", trim: "グレード", engine: "エンジン", fuel: "燃料", unknown: "不明", cannotDetermine: "判定不可",
  aiParsing: "AI補完解析", aiParsingText: "AIがNHTSAで不足している車両情報を解析中…", aiFailed: "AI補完解析に失敗", aiCandidate: "AI候補車両", sourcedInference: "出典付き推定", unverified: "未検証", confidence: "信頼度", confidenceHigh: "高", confidenceMedium: "中", confidenceLow: "低",
  possibleModels: "候補車種", candidateNotice: "候補であり確定結果ではありません", lowConfidence: "低信頼度", possibleTrims: "候補グレード：", noMoreAttributes: "追加情報なし", manualTitle: "車種を手動検索", manualIntro: "VIN不要。車両属性を順番に選択してください。", lookupMethods: "車種検索方法", select: "選択：", loading: "読込中…", noTrim: "グレードなし", noEngine: "エンジン情報なし",
  currentVehicle: "現在の車両", noMoreData: "追加構成データなし", fullMatch: "完全一致", trimMatch: "グレード一致", modelMatch: "車種一致", startFromYear: "年式から順に車種を絞り込みます", specifications: "車両仕様詳細", nhtsaSource: "データ元 · NHTSA vPIC", modelSource: "車種データ · D1 + NHTSA CVS",
  searchingImage: "同型車の参考画像を検索中…", referenceImage: "同型車参考画像", author: "作者：", commonsContributor: "Wikimedia Commons投稿者", imageGallery: "車両参考画像ギャラリー", viewImage: "参考画像を表示", inferredReferenceImage: "AI推定車種の参考画像", inferredImageNotice: "AIの最上位候補車種を使って検索した画像です。外観の参考用であり、VINの車種確定を意味しません。", viewLicense: "ライセンス", licenseAtSource: "出典ページを参照", viewSource: "画像の出典 ↗", noImage: "Wikimedia Commonsに信頼できる同型車画像がありません", queriedVin: "検索VIN", vehicleCriteria: "車両条件", noStandardName: "NHTSAは標準車種名を返しませんでした", noSummary: "車両概要なし", nhtsaListed: "NHTSA登録あり", loadingSpecs: "車両仕様を読込中…", modelReference: "車種単位の参考情報",
  basicInfo: "基本情報", series: "シリーズ", vehicleType: "車両タイプ", powertrain: "パワートレイン", displacement: "排気量", cylinders: "気筒数", engineLayout: "エンジン構成", engineModel: "エンジン型式", horsepower: "出力", primaryFuel: "主燃料", secondaryFuel: "副燃料", electrification: "電動化タイプ", driveType: "駆動方式", transmission: "トランスミッション", transmissionSpeeds: "変速段数", bodyManufacturing: "ボディ・製造", doors: "ドア数", seats: "座席数", brakes: "ブレーキ", gvwr: "車両総重量区分", plantCountry: "生産国", plantState: "生産州・県", plantCity: "生産都市",
  modelInfo: "車種情報", currentTrim: "選択グレード", currentEngine: "選択エンジン", nhtsaRegistration: "NHTSA車種登録", localPaths: "ローカル構成数", availableTrims: "選択可能グレード", availableEngines: "選択可能エンジン", dimensions: "寸法・重量", length: "全長", width: "全幅", height: "全高", wheelbase: "ホイールベース", curbWeight: "車両重量", frontTrack: "前輪トレッド", rearTrack: "後輪トレッド", weightDistribution: "前後重量配分", dataScope: "データ範囲", specSource: "仕様データ元", configSource: "構成データ元", localDb: "ローカル5階層車種DB", dataLevel: "データ粒度", modelData: "車種単位参考データ", missing: "情報なし", vinSpecsNote: "この欄にはNHTSA vPICが現在のVINに返した情報のみを表示します。「情報なし」は信頼できる値が返されなかったことを示します。", manualSpecsNote: "選択した年式・メーカー・車種から車種単位の仕様を取得します。寸法はNHTSA Canadian Vehicle Specifications、構成数はローカルD1由来です。実VINがなければ工場、正確な駆動方式、製造番号は特定できません。", scopeNote: "画像、市場価格、現在販売中の仕様はvPICデータに含まれません。",
  vinGuide: "VINフィールド説明", vinChars: "VIN文字", determined: "確定", parsingStructure: "VIN構造を解析中…", queriedVinCaption: "NHTSA検索VIN", pseudoVin: "17桁構造パターン", allChars: "全ての文字は検索VINから取得", starUnknown: "は現在特定できない文字", vinDiagram: "VIN構造図", wmi: "WMI 製造者", vds: "VDS 車両特性", checkDigit: "チェック桁", modelYear: "モデル年式", plant: "組立工場", serial: "製造番号", segmentDetails: "セグメント説明", nhtsaSegmentHint: "各セグメントにNHTSA vPIC結果を表示します。", manualSegmentHint: "VINはメーカー固有規則に従うため、車種名だけでは逆算できません。", vinProvided: "VIN入力済み", pending: "未確定", nhtsaQueryResult: "NHTSA結果", important: "重要", statsLabel: "データベース概要", noVinYear: "VINから有効な年式を取得できません。手動検索をご利用ください。", noLocalMake: "年式は判定できましたが、ローカルDBに該当メーカーがありません。", noLocalModel: "メーカーは一致しましたが、ローカルDBに該当車種がありません。", localTrimMatched: "ローカル車種DBでグレードが一致しました。", localModelMatched: "ローカル車種DBで車種が一致しました。", randomVinFailed: "ランダムVINを取得できません：", error_database: "車種データベースを読み込めませんでした", error_vehicleQuery: "車種検索に失敗しました", error_DATABASE_NOT_READY: "車種データベースがまだインポートされていません", error_DATABASE_ERROR: "車種データベースの検索に失敗しました", error_INVALID_ARGUMENT: "車種検索パラメータが無効です", error_INVALID_JSON: "リクエスト形式が無効です", error_INVALID_VIN: "VINは17文字で、I・O・Qは使用できません", error_INVALID_VEHICLE: "必要な車両パラメータが不足しています", error_VIN_UNAVAILABLE: "VIN解析サービスは一時的に利用できません", error_VIN_PATTERN_UNAVAILABLE: "VINフィールド説明を一時的に生成できません", error_VEHICLE_DETAILS_UNAVAILABLE: "車両詳細を一時的に読み込めません", error_IMAGE_LOOKUP_UNAVAILABLE: "車両参考画像を一時的に読み込めません", error_RANDOM_VIN_UNAVAILABLE: "ランダムVINサービスは一時的に利用できません。後でもう一度お試しください。", error_GEMINI_NOT_CONFIGURED: "AI補完解析が設定されていません", error_GEMINI_TIMEOUT: "AI補完解析がタイムアウトしました。再度お試しください。", error_GEMINI_RATE_LIMITED: "AIの利用枠は一時的に利用できません。後でもう一度お試しください。", error_GEMINI_AUTH_FAILED: "AIサービスの認証に失敗しました。サービス設定を確認してください。", error_GEMINI_UNAVAILABLE: "AI補完解析は一時的に利用できません", footer: "VINデータはNHTSA vPIC由来。AI推定と検索結果は車種識別の参考情報です。",
};

export function translate(locale: Locale, key: string) {
  return messages[locale][key] ?? messages.en[key] ?? messages.zh[key] ?? key;
}
